GET http://localhost:3000/players/

###
GET http://localhost:3000/players/9

###
PUT http://localhost:3000/players/9
Content-Type: application/json

{
  "playerName": "Raju"
}

###
GET http://localhost:3000/matches/3

###
GET http://localhost:3000/players/2/matches


###
GET http://localhost:3000/player_match_score/

###
GET http://localhost:3000/matches/1/players

###
GET http://localhost:3000/players/1/playerScores